### 3.2.4 시그모이드 함수 구현하기

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

신경망에서는 활성화 함수로 비선형을 써야한다. 선형함수를 이용하면 신경망의 층을 깊게 하는 의미가 없어지기 때문이다.

### 3.2.7 Relu 함수

In [3]:
def relu(x):
    return np.maximum(0, x)

## 3.3 다차원 배열의 계산

In [4]:
import numpy as np
A= np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [5]:
np.ndim(A)  # 배열의 차원 수를 확인

1

In [6]:
A.shape

(4,)

In [7]:
A.shape[0]

4

In [8]:
B=np.array([[1,2], [3,4], [5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
np.ndim(B)

2

In [10]:
B.shape

(3, 2)

In [11]:
B = np.array([7, 8])
print(B)

[7 8]


In [12]:
A = np.array([[1,2], [3,4], [5,6]])
A.shape

(3, 2)

### 3.5.1 항등함수와 소프트맥스 함수 구현

In [13]:
def softmax(a) :
    c= np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [14]:
softmax(10)

1.0

In [17]:
softmax(-5)

1.0

In [18]:
a = np.array([0.3,2.9,4.0])
y = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]


In [19]:
np.sum(y)

1.0

## 3.6 손글씨 숫자 인식
- 신경망의 순전파
- MNIST 데이터셋 0~9 숫자 train 60,000장 test 10,000장

In [4]:

import sys
import os
import pickle
import numpy as np
sys.path.append(os.pardir)  # 부모 디렉터리의 파일을 가져올 수 있도록 설정
from dataset.mnist import load_mnist
from common.functions import sigmoid, softmax


ModuleNotFoundError: No module named 'dataset.mnist'

In [6]:
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True,
                                                  normalize=False)

NameError: name 'load_mnist' is not defined